name: Go

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23"

    - name: Build
      run: go build -v ./...

    - name: Check Catalogue
      run: |
        BASE_DIR="contrib" go run ./contrib/_gen -v

    - name: AUR build test
      run: make aurtest

    - name: Test
      run: make test
